/**
 * MlfHistory — Marginal Loss Factor chart for operational wind /
 * solar / hybrid projects. Three tabbed views over the same dataset:
 *
 *   - Scatter   : every project as a dot. X = latest MLF, Y = effective
 *                 $/MWh (latest MLF × state RRP). Colour by state.
 *                 Easiest read for outliers + REZ clusters.
 *   - Box       : per-state per-FY MLF distribution (P25 / median /
 *                 P75 / min / max). Time on x-axis, MLF on y. Faceted
 *                 by state. Spots structural drift.
 *   - Time      : median MLF per state over time as a line chart.
 *                 Cleanest temporal view; companion to Box.
 *
 * Data is loaded from mlf-history.json, which is generated by
 * `pipeline/importers/import_mlf_history.py` from the AEMO MLF PDFs.
 */
import { useEffect, useMemo, useState } from 'react'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  ScatterChart, Scatter, ZAxis, ReferenceLine,
  LineChart, Line, Legend, ErrorBar,
} from 'recharts'

interface PerProject {
  id: string
  name: string
  state: string
  technology: string
  capacity_mw: number | null
  mlf_by_year: Record<string, number>
  latest_fy: string
  latest_mlf: number
}

interface StateSummary {
  state: string
  fy: string
  n: number
  p25: number
  median: number
  p75: number
  min: number
  max: number
}

interface MlfHistoryData {
  generated_at: string
  fy_list: string[]
  states: string[]
  per_project: PerProject[]
  state_summaries: StateSummary[]
  state_recent_rrp: Record<string, number>
  methodology: Record<string, string>
  sources: { fy: string; title: string; url: string }[]
}

const STATE_COLORS: Record<string, string> = {
  NSW: '#3b82f6', // blue
  VIC: '#a855f7', // purple
  QLD: '#f59e0b', // amber
  SA:  '#10b981', // emerald
  TAS: '#ec4899', // pink
}

type Tab = 'scatter' | 'box' | 'time'

export default function MlfHistory() {
  const [data, setData] = useState<MlfHistoryData | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [tab, setTab] = useState<Tab>('scatter')

  useEffect(() => {
    const base = import.meta.env.BASE_URL ?? '/'
    fetch(`${base}data/analytics/intelligence/mlf-history.json`)
      .then(r => r.ok ? r.json() : Promise.reject(`HTTP ${r.status}`))
      .then(setData)
      .catch(e => setError(String(e)))
  }, [])

  if (error) return (
    <div className="bg-[var(--color-bg-card)] border border-[var(--color-border)] rounded-xl p-5">
      <p className="text-sm text-red-400">Failed to load MLF history: {error}</p>
    </div>
  )
  if (!data) return (
    <div className="bg-[var(--color-bg-card)] border border-[var(--color-border)] rounded-xl p-5">
      <p className="text-sm text-[var(--color-text-muted)] italic">Loading MLF history…</p>
    </div>
  )

  const latestFy = data.fy_list[data.fy_list.length - 1]

  return (
    <div className="bg-[var(--color-bg-card)] border border-[var(--color-border)] rounded-xl overflow-hidden">
      {/* Header */}
      <div className="px-5 py-4 border-b border-[var(--color-border)]">
        <div className="flex items-baseline justify-between gap-3 flex-wrap mb-2">
          <h3 className="text-lg font-semibold text-[var(--color-text)]">
            Marginal Loss Factors — operational wind / solar / hybrid
          </h3>
          <span className="text-[10px] font-mono text-[var(--color-text-muted)]">
            {data.per_project.length} projects · {data.fy_list.length} years · latest FY {latestFy}
          </span>
        </div>
        <p className="text-xs text-[var(--color-text-muted)] leading-relaxed max-w-3xl">
          AEMO publishes a marginal loss factor per generator per financial year. MLF &lt; 1.0 means
          the generator receives less than the regional reference price per MWh; structural MLF
          decline is one of the largest unmodelled revenue risks for renewable projects.
        </p>

        {/* Tab toggle */}
        <div className="inline-flex rounded-lg overflow-hidden border border-[var(--color-border)] mt-3">
          {([
            { id: 'scatter', label: 'Per-project scatter' },
            { id: 'box',     label: 'Box-and-whisker by state' },
            { id: 'time',    label: 'State median over time' },
          ] as { id: Tab; label: string }[]).map(t => (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={`text-xs px-3 py-1.5 font-semibold transition-colors ${
                tab === t.id
                  ? 'bg-[var(--color-primary)] text-white'
                  : 'bg-transparent text-[var(--color-text-muted)] hover:bg-[var(--color-bg-elevated)]'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {/* Tab content */}
      <div className="p-5">
        {tab === 'scatter' && <ScatterTab data={data} />}
        {tab === 'box' && <BoxTab data={data} />}
        {tab === 'time' && <TimeTab data={data} />}
      </div>

      {/* Methodology + sources */}
      <details className="border-t border-[var(--color-border)] px-5 py-3 group">
        <summary className="text-[11px] text-[var(--color-text-muted)] cursor-pointer hover:text-[var(--color-text)] flex items-center gap-2">
          <span>Methodology &amp; sources</span>
          <span className="group-open:rotate-180 transition-transform">▾</span>
        </summary>
        <div className="text-[11px] text-[var(--color-text-muted)] leading-relaxed pt-2 space-y-2">
          {Object.entries(data.methodology).map(([k, v]) => (
            <div key={k}><strong className="text-[var(--color-text)]">{k.replace(/_/g, ' ')}:</strong> {v}</div>
          ))}
          <div className="pt-1">
            <strong className="text-[var(--color-text)]">Sources:</strong>{' '}
            {data.sources.map((s, i) => (
              <span key={s.url}>
                <a href={s.url} target="_blank" rel="noopener" className="text-[var(--color-primary)] hover:underline">{s.title}</a>
                {i < data.sources.length - 1 ? ' · ' : ''}
              </span>
            ))}
          </div>
        </div>
      </details>
    </div>
  )
}

// ============================================================
// Tab 1 — Per-project scatter
// ============================================================

function ScatterTab({ data }: { data: MlfHistoryData }) {
  // Each project: x = latest MLF, y = effective $/MWh = MLF × state RRP
  const points = useMemo(() => data.per_project.map(p => {
    const rrp = data.state_recent_rrp[p.state] ?? null
    const effective = rrp != null ? p.latest_mlf * rrp : null
    return {
      id: p.id, name: p.name, state: p.state, technology: p.technology,
      capacity_mw: p.capacity_mw, mlf: p.latest_mlf, rrp, effective,
    }
  }).filter(p => p.effective != null), [data])

  // Show RRP reference lines (horizontal, per state) — but as a backdrop
  return (
    <div>
      <p className="text-[11px] text-[var(--color-text-muted)] mb-3 italic">
        Each dot is one operational project. X-axis: latest published MLF. Y-axis: effective
        $/MWh = MLF × state median RRP (last 12 months). Lower-left = MLF + RRP both weak;
        upper-right = strongest revenue zone. Colour by state.
      </p>
      <ResponsiveContainer width="100%" height={400}>
        <ScatterChart margin={{ top: 12, right: 20, left: 4, bottom: 28 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.15)" />
          <XAxis
            type="number"
            dataKey="mlf"
            domain={[0.7, 1.05]}
            tick={{ fontSize: 11, fill: 'rgb(148,163,184)' }}
            label={{ value: 'Latest MLF', position: 'bottom', offset: 8, fill: 'rgb(148,163,184)', fontSize: 11 }}
          />
          <YAxis
            type="number"
            dataKey="effective"
            tick={{ fontSize: 11, fill: 'rgb(148,163,184)' }}
            label={{ value: 'Effective $/MWh', angle: -90, position: 'insideLeft', fill: 'rgb(148,163,184)', fontSize: 11 }}
          />
          <ZAxis type="number" dataKey="capacity_mw" range={[36, 220]} name="MW" />
          <Tooltip
            cursor={{ strokeDasharray: '3 3' }}
            contentStyle={{ backgroundColor: 'rgb(15,23,42)', border: '1px solid rgb(51,65,85)', borderRadius: 8, fontSize: 11 }}
            labelStyle={{ color: 'rgb(241,245,249)', fontWeight: 600 }}
            formatter={(value, name) => {
              if (name === 'mlf') return [(value as number).toFixed(4), 'MLF']
              if (name === 'effective') return [`$${(value as number).toFixed(0)}/MWh`, 'Effective']
              return [value, name]
            }}
            content={(props) => {
              if (!props.active || !props.payload?.length) return null
              const p = props.payload[0].payload as typeof points[number]
              return (
                <div className="bg-[var(--color-bg)] border border-[var(--color-border)] rounded-md p-2 text-[11px] shadow-md">
                  <p className="font-semibold text-[var(--color-text)]">{p.name}</p>
                  <p className="text-[var(--color-text-muted)]">
                    {p.state} · {p.technology} · {p.capacity_mw} MW
                  </p>
                  <div className="mt-1 font-mono">
                    <p>MLF: <span className="text-[var(--color-text)]">{p.mlf.toFixed(4)}</span></p>
                    <p>State RRP: <span className="text-[var(--color-text)]">${p.rrp!.toFixed(0)}/MWh</span></p>
                    <p>Effective: <span className="text-emerald-400 font-semibold">${p.effective!.toFixed(0)}/MWh</span></p>
                  </div>
                </div>
              )
            }}
          />
          <ReferenceLine x={1.0} stroke="rgb(148,163,184)" strokeDasharray="4 4" label={{ value: 'MLF 1.0', position: 'top', fill: 'rgb(148,163,184)', fontSize: 10 }} />
          {Object.entries(STATE_COLORS).map(([state, color]) => (
            <Scatter
              key={state}
              name={state}
              data={points.filter(p => p.state === state)}
              fill={color}
            />
          ))}
          <Legend
            iconSize={8}
            wrapperStyle={{ fontSize: 11, paddingTop: 12 }}
          />
        </ScatterChart>
      </ResponsiveContainer>
    </div>
  )
}

// ============================================================
// Tab 2 — Box-and-whisker by state
// ============================================================

function BoxTab({ data }: { data: MlfHistoryData }) {
  // For each state, build a bar series of medians with error bars representing P25/P75.
  // We render each state in its own small chart, faceted vertically.
  const byState = useMemo(() => {
    const map: Record<string, StateSummary[]> = {}
    for (const s of data.state_summaries) {
      if (!map[s.state]) map[s.state] = []
      map[s.state].push(s)
    }
    for (const k in map) map[k].sort((a, b) => a.fy.localeCompare(b.fy))
    return map
  }, [data])

  return (
    <div>
      <p className="text-[11px] text-[var(--color-text-muted)] mb-4 italic">
        Per-state MLF distribution by financial year. Bar = median; whiskers = P25 / P75.
        Useful for spotting structural drift (e.g. NSW MLF compression as transmission fills).
      </p>
      <div className="grid sm:grid-cols-2 gap-4">
        {data.states.map(state => {
          const rows = byState[state] || []
          if (rows.length === 0) return null
          const chartData = rows.map(r => ({
            fy: r.fy,
            median: r.median,
            p25Error: r.median - r.p25,
            p75Error: r.p75 - r.median,
            n: r.n,
          }))
          return (
            <div key={state} className="bg-[var(--color-bg)]/40 rounded-lg border border-[var(--color-border)] p-3">
              <p className="text-xs font-semibold mb-1" style={{ color: STATE_COLORS[state] }}>{state}</p>
              <p className="text-[10px] text-[var(--color-text-muted)] mb-1">
                latest {rows[rows.length - 1].fy}: median {rows[rows.length - 1].median.toFixed(3)} · n={rows[rows.length - 1].n}
              </p>
              <ResponsiveContainer width="100%" height={180}>
                <BarChart data={chartData} margin={{ top: 6, right: 6, left: -16, bottom: 4 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.12)" />
                  <XAxis dataKey="fy" tick={{ fontSize: 10, fill: 'rgb(148,163,184)' }} />
                  <YAxis domain={[0.7, 1.05]} tick={{ fontSize: 10, fill: 'rgb(148,163,184)' }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: 'rgb(15,23,42)', border: '1px solid rgb(51,65,85)', borderRadius: 6, fontSize: 10 }}
                    formatter={(value, name) => {
                      if (name === 'median') return [(value as number).toFixed(4), 'median']
                      return [value, name]
                    }}
                  />
                  <ReferenceLine y={1.0} stroke="rgba(148,163,184,0.5)" strokeDasharray="3 3" />
                  <Bar dataKey="median" fill={STATE_COLORS[state]} barSize={20}>
                    <ErrorBar dataKey="p25Error" width={4} stroke={STATE_COLORS[state]} direction="y" />
                    <ErrorBar dataKey="p75Error" width={4} stroke={STATE_COLORS[state]} direction="y" />
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ============================================================
// Tab 3 — State median over time
// ============================================================

function TimeTab({ data }: { data: MlfHistoryData }) {
  // One line per state, x = financial year, y = median MLF
  const chartData = useMemo(() => {
    const map: Record<string, Record<string, number>> = {}
    for (const s of data.state_summaries) {
      if (!map[s.fy]) map[s.fy] = { fy: s.fy } as unknown as Record<string, number>
      map[s.fy][s.state] = s.median
    }
    return Object.values(map).sort((a, b) => String(a.fy).localeCompare(String(b.fy)))
  }, [data])

  // Compute deltas per state across the period for the headline read
  const stateDeltas = useMemo(() => {
    const out: { state: string; first: number; last: number; delta: number; fyFirst: string; fyLast: string }[] = []
    for (const state of data.states) {
      const rows = data.state_summaries.filter(s => s.state === state).sort((a, b) => a.fy.localeCompare(b.fy))
      if (rows.length < 2) continue
      const first = rows[0], last = rows[rows.length - 1]
      out.push({ state, first: first.median, last: last.median, delta: last.median - first.median, fyFirst: first.fy, fyLast: last.fy })
    }
    return out
  }, [data])

  return (
    <div>
      <p className="text-[11px] text-[var(--color-text-muted)] mb-4 italic">
        Median MLF per state across published years. Falling lines indicate structural MLF
        degradation — typically driven by congestion as renewable build-out concentrates in
        weak-grid corridors.
      </p>
      <ResponsiveContainer width="100%" height={360}>
        <LineChart data={chartData} margin={{ top: 12, right: 24, left: 4, bottom: 28 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="rgba(148,163,184,0.15)" />
          <XAxis
            dataKey="fy"
            tick={{ fontSize: 11, fill: 'rgb(148,163,184)' }}
            label={{ value: 'Financial year', position: 'bottom', offset: 6, fill: 'rgb(148,163,184)', fontSize: 11 }}
          />
          <YAxis
            domain={[0.85, 1.0]}
            tick={{ fontSize: 11, fill: 'rgb(148,163,184)' }}
            label={{ value: 'Median MLF', angle: -90, position: 'insideLeft', fill: 'rgb(148,163,184)', fontSize: 11 }}
          />
          <Tooltip
            contentStyle={{ backgroundColor: 'rgb(15,23,42)', border: '1px solid rgb(51,65,85)', borderRadius: 8, fontSize: 11 }}
            formatter={(value) => (value as number).toFixed(4)}
          />
          <ReferenceLine y={1.0} stroke="rgba(148,163,184,0.4)" strokeDasharray="3 3" label={{ value: '1.0 (no loss)', position: 'right', fill: 'rgb(148,163,184)', fontSize: 9 }} />
          <Legend iconSize={8} wrapperStyle={{ fontSize: 11, paddingTop: 8 }} />
          {data.states.map(state => (
            <Line
              key={state}
              type="monotone"
              dataKey={state}
              stroke={STATE_COLORS[state]}
              strokeWidth={2.4}
              dot={{ r: 3, fill: STATE_COLORS[state] }}
              activeDot={{ r: 5 }}
              connectNulls
            />
          ))}
        </LineChart>
      </ResponsiveContainer>

      {/* Deltas table */}
      <div className="mt-4 grid sm:grid-cols-5 gap-2">
        {stateDeltas.map(d => (
          <div key={d.state} className="bg-[var(--color-bg)]/40 rounded-md border border-[var(--color-border)] p-2.5">
            <p className="text-[10px] font-semibold" style={{ color: STATE_COLORS[d.state] }}>{d.state}</p>
            <p className="text-[10px] text-[var(--color-text-muted)] mt-0.5">{d.fyFirst} → {d.fyLast}</p>
            <p className="text-base font-mono font-bold mt-0.5" style={{ color: d.delta >= 0 ? '#10b981' : '#ef4444' }}>
              {d.delta >= 0 ? '+' : ''}{(d.delta * 100).toFixed(1)} pp
            </p>
            <p className="text-[10px] text-[var(--color-text-muted)] mt-0.5 font-mono">
              {d.first.toFixed(3)} → {d.last.toFixed(3)}
            </p>
          </div>
        ))}
      </div>
    </div>
  )
}
